todos:
  data:
    :initialize: true

site:
  author: Darkbright
  description: What are your plans today?

server:
  servlet:
    encoding:
      charset: utf-8
      force: true

logging:
  level:
    todoapp: debug
    org.springframework.beans: debug
    org.springframework.web: trace

