todos:
  data:
    initialize: true
  feature:
    toggles:
      auth: true
      onlineUsersCounter: false

site:
  author: SpringRunner
  description: What're your plans today?

server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: utf-8
      force: true

logging:
  level:
    todoapp: debug
    org.springframework.web: debug
